@startuml
left to right direction
!theme cerulean-outline
actor Cliente as c
actor Hotel as h

package SisteTurismo{
  usecase "Buscar hoteles" as BH
  usecase "Mostrar caracteristicas de habitaciones" as MCH
  usecase "Hacer reserva" as HR
  usecase "Mostrar disponibilidad de hoteles" as MDH
  usecase "Mostrar informe de estadisticas" as MIE
  usecase "Mostrar reporte de ocupacion" as MRO
  usecase "Registrar retroalimentacion" as RR
}

h-->MRO
h-->MIE
h-->MDH
c-->BH
c-->MCH
c-->RR
c-->HR
c-->MDH
@enduml
